name: Owasp Zap Scan

on:
  workflow_dispatch:
    inputs:
      site_url:
        description: "Type a url to scan"
        required: true

jobs:
  owasp-zap-scan:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      issues: write

    steps:
      - uses: actions/checkout@v4

      - name: ZAP Scan baseline
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: ${{inputs.site_url}}