name: All those truffles
on:
  workflow_dispatch:
    inputs:
      repo_url:
        description: "Type a repo url to scan"
        required: true
      username:
        description: "Github username"
        required: true
      ghp:
        description: "Github access token"
        required: true

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Download via wget"
        run: |
          wget https://github.com/trufflesecurity/trufflehog/releases/download/v3.41.1/trufflehog_3.41.1_linux_amd64.tar.gz
          tar -xzvf trufflehog_3.41.1_linux_amd64.tar.gz

      - name: "Scan repo"
        env:
          ghp: ${{secrets.GHP}}
        run: |
          #!/bin/bash
          echo "Now scanning ${{ inputs.repo_url }}"
          repo_url=${{ inputs.repo_url }}
          replace_with="https://${{ inputs.username }}:${{ inputs.ghp }}@"
          repo_url=${repo_url/https:\/\//$replace_with}
          ./trufflehog git $repo_url
